services:
  postgres:
    hostname: postgres
    container_name: pantheon-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pantheon-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anish@developforgood.org
      PGADMIN_DEFAULT_PASSWORD: anish
    ports:
      - "8889:80"
    hostname: pgadmin
    depends_on:
      - postgres
