name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: develop-for-good
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/develop-for-good/dfg/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: Build image
        run: |-
          docker build -t scipio:alpha . &&
          docker tag scipio ${{ env.GAR_LOCATION }}/scipio:latest

        working-directory: .
      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}/scipio:latest
